apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: osa-ingress
  annotations:
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-methods: "PUT, GET, POST, OPTIONS, DELETE"
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
    nginx.ingress.kubernetes.io/cors-allow-headers: "Content-Type"
    nginx.ingress.kubernetes.io/rewrite-target: "/$2" # Note1 at the end of the file
spec:
  rules:
  - host: osa.localhost
    http:
      paths:
      - path: /fms(/|$)(.*) # Note1 at the end of the file
        backend:
          serviceName: osa-filemanagementservice
          servicePort: 8080
      - path: /minio(/|$)(.*) # Note1 at the end of the file
        backend:
          serviceName: osa-storage
          servicePort: 9000
      - path: /echo(/|$)(.*) # Note1 at the end of the file
        backend:
          serviceName: demo-echo-service
          servicePort: 80

# Note1:  See https://kubernetes.github.io/ingress-nginx/examples/rewrite/
