apiVersion: v1
data:
  MINIO_ACCESS_KEY: fms
  MINIO_DEFAULT_BUCKET: fms-default
  MINIO_HOST: osa-storage
  MINIO_PORT: "9000"
  MYSQL_DBNAME: fms
  MYSQL_HOST: osa-db
  MYSQL_PORT: "3306"
  MYSQL_ROOT_USERNAME: root
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"kind":"ConfigMap","apiVersion":"v1","metadata":{"name":"osa-filemanagementservice-env-file","creationTimestamp":null},"data":{"MINIO_ACCESS_KEY":"fms","MINIO_DEFAULT_BUCKET":"fms-default","MINIO_HOST":"osa-storage","MINIO_PORT":"9000","MYSQL_DBNAME":"fms","MYSQL_HOST":"osa-db","MYSQL_PORT":"3306","MYSQL_ROOT_USERNAME":"root"}}
  creationTimestamp: "2020-01-23T23:08:25Z"
  name: osa-filemanagementservice-env-file
  namespace: default
  resourceVersion: "583"
  selfLink: /api/v1/namespaces/default/configmaps/osa-filemanagementservice-env-file
  uid: aee207fb-0587-4107-a3fb-f40294a08b59
