apiVersion: v1
data:
  MINIO_SECRET_KEY: ZXhhbXBsZTE=
  MYSQL_ROOT_PASSWORD: ZXhhbXBsZQ==
kind: Secret
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"kind":"Secret","apiVersion":"v1","metadata":{"name":"osa-filemanagementservice-secret-file","creationTimestamp":null},"data":{"MINIO_SECRET_KEY":"ZXhhbXBsZTE=","MYSQL_ROOT_PASSWORD":"ZXhhbXBsZQ=="}}
  creationTimestamp: "2020-01-20T00:06:12Z"
  name: osa-filemanagementservice-secret-file
  namespace: default
  resourceVersion: "8935"
  selfLink: /api/v1/namespaces/default/secrets/osa-filemanagementservice-secret-file
  uid: cba5ee7d-ea78-4b27-9d6f-c0a0b85c2dac
type: Opaque
