apiVersion: apps/v1
kind: Deployment
metadata:
  name: osa-apigw
spec:
  selector:
    matchLabels:
      app: osa-apigw
  template:
    metadata:
      labels:
        app: osa-apigw
    spec:
      containers:
      - name: osa-apigw
        image: apigw-prod:v0
        ports:
        - containerPort: 9090
      restartPolicy: Always
